import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Footer from './components/ui/Footer'
import Navbar from './components/ui/Navbar'
const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en" className="font-satoshi">
			<Navbar />
			<body className={inter.className}>{children}</body>
			<Footer />
		</html>
	)
}
