import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Footer from './components/ui/Footer'
import Navbar from './components/ui/Navbar'
import Sidebar from './components/ui/Sidebar'
const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'DigiSignID',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en" className="font-satoshi">
			<body className={inter.className}>
				<Sidebar />
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	)
}
